### ISSUE TITLE
Service Principal created via Function App

### ISSUE THREAD

**Issue by PirteaAdrian** [Azure/azure-app-service-authentication#1]
Once AuthSettings is enabled and integrated with Azure AD an app registration can be created which has secret's validity for 10 years and both client id and its secret are visible in portal anytime, meaning that anyone who has necessary permission over that function app can take those credentials and use them for other purpose. I would like to block this behaviour but for the moment is not possible via azure policy, because of limitation occurs due to this config/AuthSettings resource not being exposed completely, so Policy cannot evaluate it.

**Comment by aaronpowell** [comment]
This repo isn't the one you're looking for regarding support for this problem. I'd suggest heading over to Tech Communities and asking there: https://techcommunity.microsoft.com/t5/azure/ct-p/Azure
