### ISSUE TITLE
Issuer Url doesn't match Directory (tenant) ID when Authentication is setup using Express method -> existing app

### ISSUE THREAD

**Issue by ShubhamSonawane** [Azure/azure-app-service-authentication#2]
Hi,
Not sure if this is the correct repository. When we turn on easy auth for a web app, and try to browse the url, we get error 500 instead of website redirecting to microsoft login page. I am using express option and selecting an existing app already created in Azure AD -> App registrations. On further investigating, after switching to advance option in Easy Auth, we found out that the Issuer URL is different than the Directory (tenant) ID from app in app registrations. 

![img3](https://user-images.githubusercontent.com/20298268/98348097-4ef9ff80-203e-11eb-869a-e55d0f874a43.png)
![img1](https://user-images.githubusercontent.com/20298268/98348102-502b2c80-203e-11eb-981e-7c1a4037a1c2.png)
![img2](https://user-images.githubusercontent.com/20298268/98348107-50c3c300-203e-11eb-813f-66754ce46abf.png)

On replacing the Issuer URL with the Tenant ID, the webapp works fine.

Any suggestions/thoughts on why easy auth is assigning wrong issuer URL?

**Comment by aaronpowell** [comment]
Sorry, this isn't the correct place for this question. I'd suggest asking on [TechCommunities](https://techcommunity.microsoft.com/t5/azure/ct-p/Azure).
